// Generated by CoffeeScript 1.7.1
(function() {
  var Shop,
    __slice = [].slice;

  Shop = (function() {
    function Shop(shopId, client) {
      this.shopId = shopId;
      this.client = client;
    }

    Shop.prototype.find = function(cb) {
      return this.client.get("/shops/" + this.shopId, function(err, status, body, headers) {
        if (err) {
          return cb(err);
        }
        if (status !== 200) {
          return cb(new Error('Get shop error'));
        } else {
          return cb(null, body, headers);
        }
      });
    };

    Shop.prototype.featuredListings = function(_arg, cb) {
      var limit, offset, params, secret, token, _ref;
      token = _arg.token, secret = _arg.secret, limit = _arg.limit, offset = _arg.offset;
      params = {};
      if (limit != null) {
        params.limit = limit;
      }
      if (offset != null) {
        params.offset = offset;
      }
      (_ref = this.client).get.apply(_ref, ["/shops/" + this.shopId + "/listings/featured", token, secret].concat(__slice.call(params), [function(err, status, body, headers) {
        if (err) {
          return cb(err);
        }
        if (status !== 200) {
          return cb(new Error('Get featured listings error'));
        } else {
          return cb(null, body, headers);
        }
      }]));
      return {
        findAllShopTransactions: function(_arg1, cb) {
          var limit, offset, page, secret, token, _ref1;
          token = _arg1.token, secret = _arg1.secret, limit = _arg1.limit, offset = _arg1.offset, page = _arg1.page;
          params = {};
          if (limit != null) {
            params.limit = limit;
          }
          if (offset != null) {
            params.offset = offset;
          }
          if (page != null) {
            params.page = page;
          }
          return (_ref1 = this.client).get.apply(_ref1, ["/shops/" + this.shopId + "/transactions", token, secret].concat(__slice.call(params), [function(err, status, body, headers) {
            if (err) {
              return cb(err);
            }
            if (status !== 200) {
              return cb(new Error('Get all transactions error'));
            } else {
              return cb(null, body, headers);
            }
          }]));
        }
      };
    };

    return Shop;

  })();

  module.exports = Shop;

}).call(this);
